version: 2
jobs:
  build-and-test:

    # Specify the Xcode version to use
    macos:
      xcode: "9.3.0"

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dep-{{ .Branch }}-
          - v1-dep-master-
          - v1-dep-
      - run:
          name: Update Homebrew
          command: brew update
      - run:
          name: Bootstrap Carthage
          command: scripts/bootstrap-if-needed.sh
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - vendor/bundle
            - Carthage

      # Build the app and run tests
      - run:
          name: Build and run tests
          command: fastlane scan --scheme Blues_Standards
      - store_test_results:
          path: test_output
      - store_artifacts:
          path: ~/Library/Logs/scan
          destination: scan-logs
      - store_artifacts:
          path: test_output

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
